/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governmentFactorySol from "./GovernmentFactory.sol";
export type { governmentFactorySol };
export type { NGNToken } from "./NGNToken";
export type { Property } from "./Property";
