/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governmentFactorySol from "./GovernmentFactory.sol";
export { NGNToken__factory } from "./NGNToken__factory";
export { Property__factory } from "./Property__factory";
